import SwiftUI
import SwiftData

struct PrivacyAndStorageView: View {
    @Environment(\.modelContext) private var context
    
    @Query private var items: [VaultItem]
    
    @State private var cacheSize: String = "Calculating..."
    @State private var showingClearCacheAlert = false
    @State private var showingNukeAlert = false
    
    @State private var preventCloudSync = true
    @State private var allowSiriLearning = true
    
    var body: some View {
        Form {
            Section(
                header: Text("Storage Usage"),
                footer: Text("Cached data includes temporary images generated by the VisionKit scanner. Clearing it will not delete your saved artifacts.")
            ) {
                HStack {
                    Text("Database (SwiftData)")
                    Spacer()
                    Text("\(items.count) Artifacts")
                        .foregroundColor(.secondary)
                }
                
                HStack {
                    Text("Scanner Cache")
                    Spacer()
                    Text(cacheSize)
                        .foregroundColor(.secondary)
                }
                
                Button(role: .destructive) {
                    showingClearCacheAlert = true
                } label: {
                    Text("Clear Temporary Cache")
                }
                .alert("Clear Scanner Cache?", isPresented: $showingClearCacheAlert) {
                    Button("Cancel", role: .cancel) { }
                    Button("Clear Cache", role: .destructive) {
                        clearTemporaryCache()
                    }
                } message: {
                    Text("This will free up local storage by deleting leftover temporary OCR files. Your saved receipts will remain intact.")
                }
            }
            
            Section(
                header: Text("Privacy Controls"),
                footer: Text("VaultScan processes all document scanning securely on-device. Your financial data never touches an external server unless you explicitly export it.")
            ) {
                Toggle("Prevent Cloud Syncing", isOn: $preventCloudSync)
                    .tint(.blue)
                
                Toggle("Allow Siri Learning", isOn: $allowSiriLearning)
                    .tint(.blue)
            }
            
            Section(
                header: Text("Danger Zone"),
                footer: Text("This action is permanent and cannot be undone.")
            ) {
                Button(role: .destructive) {
                    showingNukeAlert = true
                } label: {
                    HStack {
                        Text("Erase All Vault Data")
                        Spacer()
                        Image(systemName: "trash")
                    }
                }
                .alert("Erase Everything?", isPresented: $showingNukeAlert) {
                    Button("Cancel", role: .cancel) { }
                    Button("Erase All Data", role: .destructive) {
                        nukeDatabase()
                    }
                } message: {
                    Text("Are you absolutely sure? This will permanently destroy your entire SwiftData vault, including all receipts, warranties, and transaction histories.")
                }
            }
        }
        .navigationTitle("Privacy & Storage")
        #if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
        #endif
        .onAppear {
            calculateCacheSize()
        }
    }
    
    private func calculateCacheSize() {
            Task.detached(priority: .background) {
                let tempDirectoryURL = FileManager.default.temporaryDirectory
                var totalSize: Int64 = 0
                
                do {
                    let contents = try FileManager.default.contentsOfDirectory(at: tempDirectoryURL, includingPropertiesForKeys: [.fileSizeKey])
                    for url in contents {
                        let resourceValues = try url.resourceValues(forKeys: [.fileSizeKey])
                        if let fileSize = resourceValues.fileSize {
                            totalSize += Int64(fileSize)
                        }
                    }
                    
                    let formatter = ByteCountFormatter()
                    formatter.allowedUnits = [.useMB, .useKB]
                    formatter.countStyle = .file
                    
                    let calculatedString = totalSize > 0 ? formatter.string(fromByteCount: totalSize) : "0 KB"
                    
                    await MainActor.run {
                        self.cacheSize = calculatedString
                    }
                } catch {
                    await MainActor.run {
                        self.cacheSize = "Unknown"
                    }
                }
            }
        }
    
    private func clearTemporaryCache() {
        Task.detached(priority: .userInitiated) {
            let tempDirectoryURL = FileManager.default.temporaryDirectory
            
            do {
                let contents = try FileManager.default.contentsOfDirectory(at: tempDirectoryURL, includingPropertiesForKeys: nil)
                for fileURL in contents {
                    try FileManager.default.removeItem(at: fileURL)
                }
                await MainActor.run {
                    self.calculateCacheSize()
                }
            } catch {
                print("Failed to clear cache: \(error.localizedDescription)")
            }
        }
    }
    
    private func nukeDatabase() {
        Task {
            do {
                try context.delete(model: VaultItem.self)
                try context.save()
            } catch {
                print("Failed to wipe database: \(error.localizedDescription)")
            }
        }
    }
}
